### ISSUE TITLE
Fetch model and vendor information from a JSON file

### ISSUE THREAD

**Issue by jaimeperez** [simplesamlphp/simplesamlphp-module-webauthn#7]
The way it is today (with a class) is convenient, but it doesn't allow us to easily update the list. Besides, recognizing new models and vendors would need an update to the module, which is kind of an overkill.

Instead, it would be nice to have a script that can check metadata services for vendor/model lists, and dump a JSON file that we can use during authentication.

**Comment by restena-sw** [comment]
Have you seen getVendorDetails.php? This updates the list automatically when run - AAGUID.php is auto-generated from it (requires the --dev dependencies).

It's true that shipping with a snapshot of the data is suboptimal. But doing this in real-time has more drawbacks IMO:
- you have to allow SSP outbound traffic to a non-obvious target (FIDO Alliance Metadata Server)
- every installation trying to do that needs to register at the FIDO Alliance for getting an API key (the MDS is NOT public)

However, switching from an auto-generated class file to JSON is trivial - the generator script would simply use json_encode() instead of var_export(). Not sure how much good that alone does though.

**Comment by jaimeperez** [comment]
Yeah, I saw that 5 minutes after opening the issue 😅

I still think it's useful to use JSON though, for several reasons:

* We could just use a standard JSON feed from an API.
* We can treat it as an optional configuration file. In case it's missing or broken, it doesn't matter, we just miss vendor/model mapping, as opposed to a PHP fatal error if something goes wrong when generating the file.

**Comment by restena-sw** [comment]
Okay! I will change the code of getVendorDetails.php to generate JSON instead and commit one such auto-generated file.
Can you in turn do the magic you speak about, i.e. handling as optional config file?

**Comment by jaimeperez** [comment]
Thanks! I can certainly do that 😄

**Comment by restena-sw** [comment]
pretty-print json now in GitHub.

**Comment by jaimeperez** [comment]
Just saw that, yep. I'll enhance it a bit also to move it to the `bin` directory we usually put our command-line utils on, and accept the token as a parameter instead of hard-coding it in the script itself.

**Comment by jaimeperez** [comment]
Ok, it should be done now! 😄
