### ISSUE TITLE
Tests are failing due to unresolved issues reported by Psalm

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp-module-webauthn#8]

**Comment by tvdijen** [comment]
Hi @restena-sw !

Can you tell me a bit more about this lines of code:
https://github.com/simplesamlphp/simplesamlphp-module-webauthn/blob/ecdb36abc17f8b5122e366a9a9ddada0adb11e4e/lib/Auth/Process/WebAuthn.php#L140-L145

I think this will horribly fail if the entityId does not contain a forward slash, which is a perfectly valid situation (i.e.: when using a URN)

**Comment by restena-sw** [comment]
Sure. If scope is not explicitly given, the hostname is the scope.

What I implemented is a bit of a hack, given that the default IdPEntityId contains the (known-correct) hostname I would just extract it from there.

Taking it from elsewhere in the SSP or server config is certainly better, I just couldn't find a good place to take it from. I checked specifically $_SERVER['SERVER_NAME'] but that is only safe to use under specific conditions, otherwise it can contain spoofed client content.

If there is already a reliable mechanism in SSP to get the current server's hostname, then it would be better to use that of course.

**Comment by tvdijen** [comment]
How can a server variable set by the web server contain spoofed client content? That seems impossible to me..

Anyway, we have [this](https://github.com/simplesamlphp/simplesamlphp/blob/1a6c8f371d57a1d958823f60cdbe2c4783cb67e1/lib/SimpleSAML/Utils/HTTP.php#L58) utility method in place that we could rely on?

**Comment by restena-sw** [comment]
https://www.php.net/manual/en/reserved.variables.server.php

"Note: Under Apache 2, you must set UseCanonicalName = On and ServerName. Otherwise, this value reflects the hostname supplied by the client, which can be spoofed. It is not safe to rely on this value in security-dependent contexts."

The utility method uses SERVER_NAME (possibly unsafe as above) and falls back to HTTP_HOST which is in the client-sent header and always unsafe.

Still, not saying my use is any safer than that: the typical auto-generated IdP entity IDs are also generated by SSP code. If the respective code also uses the same utility method, nothing is won by my awkward parsing of the entityId. So if that's the case, at least switching to the convenience method makes things look nicer.

**Comment by tvdijen** [comment]
Ok, so I see two options here:
1. We make the scope a mandatory thing that needs to be supplied at all time
2. We fetch the hosted IDP entityId from the saml20-idp-hosted.php file, for example using this method: https://github.com/simplesamlphp/simplesamlphp/blob/1a6c8f371d57a1d958823f60cdbe2c4783cb67e1/lib/SimpleSAML/Metadata/MetaDataStorageSource.php#L138. That should catch the spoofing. It would still break if someone changed the entityId to a non-url

**Comment by restena-sw** [comment]
TBH, option 1 sounds like the more robust approach.

This topic begs the question though: is $_SERVER['SERVER_NAME'] used in other contexts that might enable an attacker to do a URL-rewrite?

**Comment by tvdijen** [comment]
I just discussed this with Jaime and we agree on option 1..
I guess a misconfiguration of your webserver can always create a situtation where you're vulnerable... Not sure if we could catch that.

**Comment by joostd** [comment]
I think we shouldn't worry about the scope and leave it optional. The scope parameter is actually optional in the Webauthn standard: 
https://www.w3.org/TR/webauthn/#CreateCred-DetermineRpId

You should only need to set it for instance when you would like to _widen_ the scope to a parent domain.

Besides, spoofing is not an issue here. Even if the scope was altered somehow, tricking the server in using a spoofed scope, Webauthn is designed to be resilient to such attacks. The client (i.e. web browser) will always use the scope derived from the URL it has retrieved when constructing clientData. As such, the token will never generate credentials or assertions for such a spoofed scope.

**Comment by tvdijen** [comment]
Ok, so I will revert the removal then and make it use Utils/HTTP::getServerHost() if not set

**Comment by tvdijen** [comment]
To summarize the discussion we had at NTW19:
- Scope can be null / unset
- If it is null, the browser will actually determine what it should be.. We don't have to be smart about it server-side, like I suggested above
- We could however be smart and derive the scope as I suggested and then compare it to the configured scope, just so we can warn the IdP-admin about misconfiguration.

I don't want to overcomplicate this PR, as this would involve a bit of work and it's mostly a nice-to-have, so I will open a separate issue

**Comment by restena-sw** [comment]
Well it is possible (but somehow contrived) to construct an example where this can be exploited, so long as the attack can happen in a third-level domain. Imagine the two sites
genuine.geocities.com and attacker.geocities.com

The actual service is on genuine.geocitites.com and uses the (implicit, unconfigured) scope "genuine.geocities.com".

The attacker launches a phishing attack leading a user to attacker.geocities.com and delivers a web page with JS code that sets the scope to "geocities.com" (which is allowed as per FIDO2 spec to widen the scope). The resulting auth data is then submitted to genuine.geocities.com.

genuine.geocities.com would /usually/ detect this as its (unconfigured, expected) scope is not "geocities.com" but "genuine.geocities.com".

But if the determination what the implicit scope should be is wrong (like in the Apache 2 bogus $_SERVER['SERVER_NAME'] case) then the attacker could trick the server-side (by sending wrong headers, or whatnot is needed to trigger the wrong derivation) to believe that "geocities.com" is the correct scope. The scope then also matches the incoming scope hash, and the transaction passes that part of validation.

TBH, the simple fix to this is by adding to the documentation "if your service doesn't control the entirety of your second-level domain, set the scope explicitly or some contrived attacks are possible".

**Comment by tvdijen** [comment]
> TBH,  the simple fix to this is by adding to the documentation "if your  service doesn't control the entirety of your second-level domain, set  the scope explicitly or some contrived attacks are possible".

I think that's all we can do and I totally agree

**Comment by restena-sw** [comment]
Okay, pushed an update to README.md with this content in.
